
parameters:
    locale: 'fr'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

 
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

  
    App\Controller\HomeController:
        tags: ['controller.service_arguments']
    
    App\Controller\PropertyController:
        arguments:
            '$em': '@doctrine.orm.default_entity_manager'
    
    App\Listener\ImageCacheSubscriber:
        tags:
            name: doctrine.event_subscriber
